name: master

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Build tunebook lilypond definition
        run: ./bin/book.sh
      - name: Build tunebook PDF
        run: docker run --rm -v $(pwd):/app -w /app iskaron/lilypond lilypond ./book.ly
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "./book.pdf"
          artifactContentType: "application/pdf"
